services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=doodlechat_db
      - POSTGRES_USER=doodleuser
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./doodlechat-pg-vol:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - doodle-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=doodlechat_db
      - DATABASE_USER=doodleuser
      - DATABASE_PASSWORD=postgres
    ports:
      - "8888:8888"
    networks:
      - doodle-network
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:8888
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - doodle-network

networks:
  doodle-network:
    driver: bridge
