### GET health check
GET localhost:8888/health
Content-Type: application/json

### GET all users
GET localhost:8888/users/
Content-Type: application/json

### GET all messages
GET localhost:8888/messages/
Content-Type: application/json

### POST new message
POST localhost:8888/messages/
Content-Type: application/json

{
  "user_id": "<valid_uuid>",
  "message": "Trying out the API"
}

### GET demo user
GET localhost:8888/users/demo-user
