spring:
  application:
    name: fe-core-challenge

  datasource:
    url: jdbc:postgresql://db:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1

  jpa:
    show-sql: true
    generate-ddl: false
    database: postgresql
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migrations,db/initial-data
    sql-migration-prefix: v
    sql-migration-separator: "-"
    baselineOnMigrate: true
server:
  port: 8888
